CREATE TABLE GENERATOR (
	GEN_NAME VARCHAR(30) NOT NULL,
	GEN_VALUE BIGINT NOT NULL DEFAULT 1000,
	PRIMARY KEY (GEN_NAME)
) ENGINE=INNODB;

CREATE TABLE USER_ACCOUNT (
	USER_ACCOUNT_KEY BIGINT NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(64),
	LAST_NAME VARCHAR(64),
	BIRTHDATE DATE,
	EMAIL VARCHAR(255) NOT NULL,
    ENABLED BIT NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	PASSWORD_RESET_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (USER_ACCOUNT_KEY),
    UNIQUE INDEX (USERNAME),
    UNIQUE INDEX (EMAIL)
) ENGINE=INNODB;

CREATE TABLE ROLE (
	ROLE_KEY BIGINT NOT NULL,
	MODULE VARCHAR(16) NOT NULL,
	ACTION VARCHAR(16) NOT NULL,
	PRIMARY KEY (ROLE_KEY)
) ENGINE=INNODB;

CREATE TABLE USER_ACCOUNT_ROLE (
	USER_ACCOUNT_KEY BIGINT NOT NULL,
	ROLE_KEY BIGINT NOT NULL,
	PRIMARY KEY(USER_ACCOUNT_KEY, ROLE_KEY),
	CONSTRAINT FK_ROLE_ACCOUNT FOREIGN KEY (ROLE_KEY) REFERENCES ROLE (ROLE_KEY),
    CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY (USER_ACCOUNT_KEY) REFERENCES USER_ACCOUNT (USER_ACCOUNT_KEY)
) ENGINE=INNODB;