CREATE TABLE GENERATOR (
	GEN_NAME VARCHAR(30) NOT NULL,
	GEN_VALUE BIGINT NOT NULL DEFAULT 1000,
	PRIMARY KEY (GEN_NAME)
) ENGINE=INNODB;

CREATE TABLE USER_ACCOUNT (
	USER_ACCOUNT_KEY BIGINT NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(64),
	LAST_NAME VARCHAR(64),
	BIRTHDATE DATE,
	EMAIL VARCHAR(255) NOT NULL,
    ENABLED BIT NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	PASSWORD_RESET_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (USER_ACCOUNT_KEY),
    UNIQUE INDEX (USERNAME),
    UNIQUE INDEX (EMAIL)
) ENGINE=INNODB;

CREATE TABLE ROLE (
	ROLE_KEY BIGINT NOT NULL,
	MODULE VARCHAR(16) NOT NULL,
	ACTION VARCHAR(16) NOT NULL,
	PRIMARY KEY (ROLE_KEY)
) ENGINE=INNODB;

CREATE TABLE USER_ACCOUNT_ROLE (
	USER_ACCOUNT_KEY BIGINT NOT NULL,
	ROLE_KEY BIGINT NOT NULL,
	PRIMARY KEY(USER_ACCOUNT_KEY, ROLE_KEY),
	CONSTRAINT FK_ROLE_ACCOUNT FOREIGN KEY (ROLE_KEY) REFERENCES ROLE (ROLE_KEY),
    CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY (USER_ACCOUNT_KEY) REFERENCES USER_ACCOUNT (USER_ACCOUNT_KEY)
) ENGINE=INNODB;

CREATE TABLE IMAGE (
	IMAGE_KEY BIGINT NOT NULL,
	CONTENT MEDIUMBLOB,
	TYPE VARCHAR(16),
	NAME VARCHAR(32) NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (IMAGE_KEY)
) ENGINE=INNODB;

CREATE TABLE REQUEST_LOG (
	REQUEST_LOG_KEY BIGINT NOT NULL,
	CREATED_DATE DATETIME NOT NULL,
	ADDRESS VARCHAR(16) NOT NULL,
	METHOD VARCHAR(7) NOT NULL,
	URI VARCHAR(128) NOT NULL,
	SESSION_ID VARCHAR(32),
	LOCALE VARCHAR(5),
	ENCODING VARCHAR(16),
	PRIMARY KEY (REQUEST_LOG_KEY)
) ENGINE=INNODB;

CREATE INDEX REQUEST_LOG_CREATED_DATE_INDEX ON REQUEST_LOG(CREATED_DATE);

CREATE TABLE REQUEST_LOG_DATA (
	REQUEST_LOG_KEY BIGINT NOT NULL,
	BODY TEXT,
	QUERY_STRING TEXT,
	PRIMARY KEY (REQUEST_LOG_KEY),
 	CONSTRAINT FK_REQUEST_LOG_BODY FOREIGN KEY (REQUEST_LOG_KEY) REFERENCES REQUEST_LOG (REQUEST_LOG_KEY),
	CONSTRAINT CHK_REQUEST_LOG_DATA CHECK (BODY IS NOT NULL OR QUERY_STRING IS NOT NULL)
 ) ENGINE=INNODB;
 
 CREATE TABLE PAGE (
	PAGE_KEY BIGINT NOT NULL,
	NAME VARCHAR(32) NOT NULL,
	TITLE VARCHAR(128) NOT NULL,
	REFERENCE VARCHAR(64) NOT NULL,
	CONTENT TEXT NOT NULL,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PAGE_KEY),
	UNIQUE INDEX (REFERENCE)
) ENGINE=INNODB;

CREATE TABLE MENU_PAGE (
	MENU_PAGE_KEY BIGINT NOT NULL,
	PAGE_KEY BIGINT NOT NULL,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	STATUS CHAR(1) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (MENU_PAGE_KEY),
	CONSTRAINT FK_MENU_PAGE FOREIGN KEY (PAGE_KEY) REFERENCES PAGE (PAGE_KEY),
	CONSTRAINT CHK_MENU_PAGE_STATUS CHECK (STATUS IN ('A', 'I'))
) ENGINE=INNODB;

CREATE TABLE CATEGORY (
	CATEGORY_KEY BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	REFERENCE VARCHAR(64) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (CATEGORY_KEY),
	UNIQUE INDEX (NAME)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE (
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	TITLE VARCHAR(128) NOT NULL,
	ARTICLE VARCHAR(128) NOT NULL,
	REFERENCE VARCHAR(64) NOT NULL,
	SALE_STATUS CHAR(1) NOT NULL,
	DESCRIPTION TEXT,
	DESCRIPTION_FULL TEXT,
	TAG_TITLE TINYTEXT,
	TAG_KEYWORDS TINYTEXT,
	TAG_DESCRIPTION TEXT,
	MAIN_IMAGE_KEY BIGINT,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ARTICLE_KEY),
	CONSTRAINT FK_PRODUCT_ARTICLE_IMAGE FOREIGN KEY (MAIN_IMAGE_KEY) REFERENCES IMAGE (IMAGE_KEY),
	CONSTRAINT CHK_PA_SALE_STATUS CHECK (SALE_STATUS IN ('E', 'I', 'O'))
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE_OPTION (
	PRODUCT_ARTICLE_OPTION_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	VALUE VARCHAR(64) NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ARTICLE_OPTION_KEY),
	UNIQUE INDEX (PRODUCT_ARTICLE_OPTION_KEY, NAME, VALUE),
	CONSTRAINT FK_PRODUCT_ARTICLE_OPTION_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE_CATEGORY (
	CATEGORY_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	PRIMARY KEY(CATEGORY_KEY, PRODUCT_ARTICLE_KEY),
	CONSTRAINT FK_CATEGORY_PRODUCT_ARTICLE FOREIGN KEY (CATEGORY_KEY) REFERENCES CATEGORY (CATEGORY_KEY),
    CONSTRAINT FK_PRODUCT_ARTICLE_CATEGORY FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT (
	PRODUCT_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	PRICE NUMERIC (10, 2),
	ACTUAL_PRICE NUMERIC (10, 2),
	QUANTITY INT,
	VERSION BIGINT NOT NULL DEFAULT 0,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	PRIMARY KEY (PRODUCT_KEY),
	CONSTRAINT FK_PRODUCT_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_PRODUCT_ARTICLE_OPTION (
	PRODUCT_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_OPTION_KEY BIGINT NOT NULL,
	PRIMARY KEY(PRODUCT_KEY, PRODUCT_ARTICLE_OPTION_KEY),
	CONSTRAINT FK_PRODUCT_PAO FOREIGN KEY (PRODUCT_KEY) REFERENCES PRODUCT (PRODUCT_KEY),
    CONSTRAINT FK_POA_PRODUCT FOREIGN KEY (PRODUCT_ARTICLE_OPTION_KEY) REFERENCES PRODUCT_ARTICLE_OPTION (PRODUCT_ARTICLE_OPTION_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE_IMAGE (
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	IMAGE_KEY BIGINT NOT NULL,
	PRIMARY KEY(PRODUCT_ARTICLE_KEY, IMAGE_KEY),
	CONSTRAINT FK_PAO_IMG FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY),
    CONSTRAINT FK_IMG_PAO FOREIGN KEY (IMAGE_KEY) REFERENCES IMAGE (IMAGE_KEY)
) ENGINE=INNODB;

CREATE TABLE PAYMENT_METHOD (
	PAYMENT_METHOD_KEY BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NOT NULL,
	STATUS CHAR(1) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PAYMENT_METHOD_KEY),
	CONSTRAINT CHK_PMT_METHOD_STATUS CHECK (ORDER_STATUS IN ('A', 'I'))
) ENGINE=INNODB;

CREATE TABLE SHIPPING_METHOD (
	SHIPPING_METHOD_KEY BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	DESCRIPTION VARCHAR(256) NOT NULL,
	COST NUMERIC (10, 2),
	STATUS CHAR(1) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (SHIPPING_METHOD_KEY),
	CONSTRAINT CHK_SHP_METHOD_STATUS CHECK (ORDER_STATUS IN ('A', 'I'))
) ENGINE=INNODB;

CREATE TABLE `ORDER` (
	ORDER_KEY BIGINT NOT NULL,
	PHONE VARCHAR(20) NOT NULL,
	ORDER_STATUS CHAR(1) NOT NULL,
	SHIPPING_METHOD_KEY BIGINT,
	PAYMENT_METHOD_KEY BIGINT,
	TOTAL_PRODUCT_AMOUNT NUMERIC (10, 2),
	SHIPPING_COST NUMERIC (10, 2),
	TOTAL_AMOUNT NUMERIC (10, 2),
	FULL_NAME VARCHAR(64),
	EMAIL VARCHAR(128),
	ADDRESS VARCHAR(128),
	COMMENT VARCHAR(128),
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (ORDER_KEY),
	CONSTRAINT CHK_ORDER_STATUS CHECK (ORDER_STATUS IN ('N', 'Q', 'C', 'D')),
	CONSTRAINT FK_ORDER_PMT FOREIGN KEY (PAYMENT_METHOD_KEY) REFERENCES PAYMENT_METHOD (PAYMENT_METHOD_KEY),
    CONSTRAINT FK_ORDER_SHP FOREIGN KEY (SHIPPING_METHOD_KEY) REFERENCES SHIPPING_METHOD (SHIPPING_METHOD_KEY)
) ENGINE=INNODB;

CREATE TABLE ORDER_ITEM (
	ORDER_ITEM_KEY BIGINT NOT NULL,
	ORDER_KEY BIGINT NOT NULL,
	PRODUCT_KEY BIGINT NOT NULL,
	QUANTITY INT,
	PRICE NUMERIC (10, 2),
	TOTAL_AMOUNT NUMERIC (10, 2),
	VERSION BIGINT NOT NULL DEFAULT 0,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	PRIMARY KEY (ORDER_ITEM_KEY),
	CONSTRAINT FK_ORDER_ITEM_ORDER FOREIGN KEY (ORDER_KEY) REFERENCES `ORDER` (ORDER_KEY),
    CONSTRAINT FK_ORDER_ITEM_PRODUCT FOREIGN KEY (PRODUCT_KEY) REFERENCES PRODUCT (PRODUCT_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ATTRIBUTE_NUMERIC (
	PRODUCT_ATTRIBUTE_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	`GROUP` VARCHAR(32),
	NAME VARCHAR(64) NOT NULL,
	VALUE_NUMERIC NUMERIC (10, 2) NOT NULL,
	UNIT VARCHAR(4) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ATTRIBUTE_KEY),
	UNIQUE INDEX (PRODUCT_ARTICLE_KEY, NAME),
	CONSTRAINT FK_PRD_ATTR_NUM_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ATTRIBUTE_BOOLEAN (
	PRODUCT_ATTRIBUTE_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	`GROUP` VARCHAR(32),
	NAME VARCHAR(64) NOT NULL,
	VALUE_BOOLEAN BIT NOT NULL,
	DESCRIPTION VARCHAR(64),
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ATTRIBUTE_KEY),
	UNIQUE INDEX (PRODUCT_ARTICLE_KEY, NAME),
	CONSTRAINT FK_PRD_ATTR_BOOL_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ATTRIBUTE_STRING (
	PRODUCT_ATTRIBUTE_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	`GROUP` VARCHAR(32),
	NAME VARCHAR(64) NOT NULL,
	VALUE_STRING VARCHAR(64) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ATTRIBUTE_KEY),
	UNIQUE INDEX (PRODUCT_ARTICLE_KEY, NAME),
	CONSTRAINT FK_PRD_ATTR_STR_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ATTRIBUTE_LIST (
	PRODUCT_ATTRIBUTE_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	`GROUP` VARCHAR(32),
	NAME VARCHAR(64) NOT NULL,
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ATTRIBUTE_KEY),
	UNIQUE INDEX (PRODUCT_ARTICLE_KEY, NAME),
	CONSTRAINT FK_PRD_ATTR_LIST_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ATTRIBUTE_LIST_VALUES (
	PRODUCT_ATTRIBUTE_KEY BIGINT NOT NULL,
	VALUE VARCHAR(64) NOT NULL,
	UNIQUE INDEX (PRODUCT_ATTRIBUTE_KEY, VALUE),
	CONSTRAINT FK_PRD_ATTR_LIST_VALUES FOREIGN KEY (PRODUCT_ATTRIBUTE_KEY) REFERENCES PRODUCT_ATTRIBUTE_LIST (PRODUCT_ATTRIBUTE_KEY)
) ENGINE=INNODB;

CREATE TABLE CATEGORY_FILTER (
	CATEGORY_FILTER_KEY BIGINT NOT NULL,
	CATEGORY_KEY BIGINT NOT NULL,
	TYPE CHAR(4) NOT NULL,
	NAME VARCHAR(64),
	`ORDER` INT NOT NULL DEFAULT 0,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (CATEGORY_FILTER_KEY),
	CONSTRAINT FK_CTG_FILTER_CTG FOREIGN KEY (CATEGORY_KEY) REFERENCES CATEGORY (CATEGORY_KEY),
	CONSTRAINT CHK_CTG_FILTER_TYPE CHECK (TYPE IN ('sAny', 'lAll', 'nRng', 'bAll', 'bAny'))
) ENGINE=INNODB;

CREATE TABLE COMMENT (
	COMMENT_KEY BIGINT NOT NULL,
	DATE_TIME DATETIME NOT NULL,
	USER_IP VARCHAR(15) NOT NULL,
	USER_NAME VARCHAR(32) NOT NULL,
	TEXT TEXT NOT NULL,
	MODIFIED_DATE DATETIME,
	CREATED_DATE DATETIME NOT NULL,
	STATUS CHAR(1) NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (COMMENT_KEY),
	CONSTRAINT CHK_COMMENT_STATUS CHECK (STATUS IN ('A', 'I'))
) ENGINE=INNODB;

CREATE TABLE PRODUCT_COMMENT (
	COMMENT_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	MARK TINYINT NOT NULL,
	PRIMARY KEY (PRODUCT_ARTICLE_KEY, COMMENT_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_LABEL (
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	LABEL VARCHAR(32) NOT NULL,
	TYPE CHAR(1) NOT NULL,
	PRIMARY KEY (PRODUCT_ARTICLE_KEY, LABEL),
	CONSTRAINT FK_PRODUCT_LBL FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY),
	CONSTRAINT CHK_PRODUCT_LABEL_TYPE CHECK (TYPE IN ('A', 'B', 'C'))
) ENGINE=INNODB;