CREATE TABLE GENERATOR (
	GEN_NAME VARCHAR(30) NOT NULL,
	GEN_VALUE BIGINT NOT NULL DEFAULT 1000,
	PRIMARY KEY (GEN_NAME)
) ENGINE=INNODB;

CREATE TABLE USER_ACCOUNT (
	USER_ACCOUNT_KEY BIGINT NOT NULL,
	USERNAME VARCHAR(20) NOT NULL,
	FIRST_NAME VARCHAR(64),
	LAST_NAME VARCHAR(64),
	BIRTHDATE DATE,
	EMAIL VARCHAR(255) NOT NULL,
    ENABLED BIT NOT NULL,
	PASSWORD VARCHAR(80) NOT NULL,
	PASSWORD_RESET_DATE DATETIME NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (USER_ACCOUNT_KEY),
    UNIQUE INDEX (USERNAME),
    UNIQUE INDEX (EMAIL)
) ENGINE=INNODB;

CREATE TABLE ROLE (
	ROLE_KEY BIGINT NOT NULL,
	MODULE VARCHAR(16) NOT NULL,
	ACTION VARCHAR(16) NOT NULL,
	PRIMARY KEY (ROLE_KEY)
) ENGINE=INNODB;

CREATE TABLE USER_ACCOUNT_ROLE (
	USER_ACCOUNT_KEY BIGINT NOT NULL,
	ROLE_KEY BIGINT NOT NULL,
	PRIMARY KEY(USER_ACCOUNT_KEY, ROLE_KEY),
	CONSTRAINT FK_ROLE_ACCOUNT FOREIGN KEY (ROLE_KEY) REFERENCES ROLE (ROLE_KEY),
    CONSTRAINT FK_ACCOUNT_ROLE FOREIGN KEY (USER_ACCOUNT_KEY) REFERENCES USER_ACCOUNT (USER_ACCOUNT_KEY)
) ENGINE=INNODB;

CREATE TABLE CATEGORY (
	CATEGORY_KEY BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	REFERENCE VARCHAR(64) NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (CATEGORY_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE (
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	TITLE VARCHAR(128) NOT NULL,
	ARTICLE VARCHAR(128) NOT NULL,
	REFERENCE VARCHAR(64) NOT NULL,
	DESCRIPTION TEXT,
	DESCRIPTION_FULL TEXT,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE_OPTION (
	PRODUCT_ARTICLE_OPTION_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	NAME VARCHAR(64) NOT NULL,
	VALUE VARCHAR(64) NOT NULL,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_ARTICLE_OPTION_KEY),
	UNIQUE INDEX (PRODUCT_ARTICLE_OPTION_KEY, NAME, VALUE),
	CONSTRAINT FK_PRODUCT_ARTICLE_OPTION_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_ARTICLE_CATEGORY (
	CATEGORY_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	PRIMARY KEY(CATEGORY_KEY, PRODUCT_ARTICLE_KEY),
	CONSTRAINT FK_CATEGORY_PRODUCT_ARTICLE FOREIGN KEY (CATEGORY_KEY) REFERENCES CATEGORY (CATEGORY_KEY),
    CONSTRAINT FK_PRODUCT_ARTICLE_CATEGORY FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT (
	PRODUCT_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_KEY BIGINT NOT NULL,
	SALE_STATUS CHAR(1) NOT NULL,
	PRICE NUMERIC (10, 2),
	ACTUAL_PRICE NUMERIC (10, 2),
	QUANTITY INT,
	VERSION BIGINT NOT NULL DEFAULT 0,
	PRIMARY KEY (PRODUCT_KEY),
	CONSTRAINT FK_PRODUCT_PA FOREIGN KEY (PRODUCT_ARTICLE_KEY) REFERENCES PRODUCT_ARTICLE (PRODUCT_ARTICLE_KEY)
) ENGINE=INNODB;

CREATE TABLE PRODUCT_PRODUCT_ARTICLE_OPTION (
	PRODUCT_KEY BIGINT NOT NULL,
	PRODUCT_ARTICLE_OPTION_KEY BIGINT NOT NULL,
	PRIMARY KEY(PRODUCT_KEY, PRODUCT_ARTICLE_OPTION_KEY),
	CONSTRAINT FK_PRODUCT_PAO FOREIGN KEY (PRODUCT_KEY) REFERENCES PRODUCT (PRODUCT_KEY),
    CONSTRAINT FK_POA_PRODUCT FOREIGN KEY (PRODUCT_ARTICLE_OPTION_KEY) REFERENCES PRODUCT_ARTICLE_OPTION (PRODUCT_ARTICLE_OPTION_KEY)
) ENGINE=INNODB;