INSERT INTO GENERATOR (GEN_NAME) VALUES ('USER_ACCOUNT_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('ROLE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('CATEGORY_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('PRODUCT_ARTICLE_GEN');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('PRODUCT_ARTICLE_OPTION');
INSERT INTO GENERATOR (GEN_NAME) VALUES ('PRODUCT_GEN');