
INSERT INTO USER_ACCOUNT (USER_ACCOUNT_KEY, USERNAME, FIRST_NAME, LAST_NAME, BIRTHDATE, EMAIL, ENABLED, PASSWORD, PASSWORD_RESET_DATE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_ACCOUNT_GEN'), 'makseemka', 'Максим', 'Драгун', '1991-02-04', 'max@dragberry.net', true, '$2a$04$QjQ1pKIFt.KZMUD/ZjhWFOBBLYOshUh9OMIZ5y76t61A2mNV8qGSG', '2017-08-25');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_ACCOUNT_GEN';
INSERT INTO USER_ACCOUNT (USER_ACCOUNT_KEY, USERNAME, FIRST_NAME, LAST_NAME, BIRTHDATE, EMAIL, ENABLED, PASSWORD, PASSWORD_RESET_DATE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_ACCOUNT_GEN'), 'chueshkovu', 'Юрий', 'Чуешков', '1994-08-25', 'chueshkov@dragberry.net', true, '$2a$04$QjQ1pKIFt.KZMUD/ZjhWFOBBLYOshUh9OMIZ5y76t61A2mNV8qGSG', '2017-08-25');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_ACCOUNT_GEN';
INSERT INTO USER_ACCOUNT (USER_ACCOUNT_KEY, USERNAME, FIRST_NAME, LAST_NAME, BIRTHDATE, EMAIL, ENABLED, PASSWORD, PASSWORD_RESET_DATE)
	VALUES ((SELECT MAX(GEN_VALUE) FROM GENERATOR WHERE GEN_NAME = 'USER_ACCOUNT_GEN'), 'test', 'Тест', 'Тестов', '1994-08-25', 'test@dragberry.net', true, '$2a$04$QjQ1pKIFt.KZMUD/ZjhWFOBBLYOshUh9OMIZ5y76t61A2mNV8qGSG', '2017-08-25');
UPDATE GENERATOR SET GEN_VALUE = GEN_VALUE + 1 WHERE GEN_NAME = 'USER_ACCOUNT_GEN';

-- makseemka
-- Registrations roles
INSERT INTO USER_ACCOUNT_ROLE (USER_ACCOUNT_KEY, ROLE_KEY) 
	VALUES (
		(SELECT USER_ACCOUNT_KEY FROM USER_ACCOUNT WHERE USERNAME = 'makseemka'), 
		(SELECT ROLE_KEY FROM ROLE WHERE MODULE = 'ADMIN' AND ACTION = 'VIEW'));
